### DISCUSSION TITLE
stuck plotting processes on phase 3

### DISCUSSION THREAD

**Discussion by berejznoy** [swar/Swar-Chia-Plot-Manager#107] [Q&A]
Hello.I have the stuck processes of plotting

![image](https://user-images.githubusercontent.com/6411006/116803988-02423d80-ab24-11eb-8512-42bc30bd9913.png)

**Comment by swar** [comment]
@berejznoy  sorry I need more information than just this. I am not sure what I am looking at or how its stuck. Is the log moving?

**Comment by berejznoy** [comment]
Hello. I have some stuck processes every time I start plot manager.
 
Two processes stuck on this screenshot (wd and hp)
![image](https://user-images.githubusercontent.com/6411006/116965663-fcc92c80-acb6-11eb-8fec-5025adb01e98.png)
[wd_2021-05-03_12_35_01_669465.log](https://github.com/swar/Swar-Chia-Plot-Manager/files/6419208/wd_2021-05-03_12_35_01_669465.log) - log here

It is my configuration
```
- name: hp
    max_plots: 6
    farmer_public_key:
    pool_public_key:
    temporary_directory: G:\chia_temp
    temporary2_directory:
    destination_directory: D:\chia_plot
    size: 32
    bitfield: true
    threads: 4
    buckets: 128
    memory_buffer: 3416
    max_concurrent: 6
    max_concurrent_with_start_early: 6
    stagger_minutes: 1
    max_for_phase_1: 1
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false

  - name: wd
    max_plots: 3
    farmer_public_key:
    pool_public_key:
    temporary_directory: H:\chia_temp
    temporary2_directory:
    destination_directory: D:\chia_plot
    size: 32
    bitfield: true
    threads: 4
    buckets: 128
    memory_buffer: 3416
    max_concurrent: 3
    max_concurrent_with_start_early: 3
    stagger_minutes: 0
    max_for_phase_1: 1
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false

  - name: samsung
    max_plots: 1
    farmer_public_key:
    pool_public_key:
    temporary_directory: E:\chia_temp
    temporary2_directory:
    destination_directory: D:\chia_plot
    size: 32
    bitfield: true
    threads: 4
    buckets: 128
    memory_buffer: 3416
    max_concurrent: 1
    max_concurrent_with_start_early: 1
    stagger_minutes: 0
    max_for_phase_1: 1
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false

```
