### DISCUSSION TITLE
What should I type as a list in destination_directory?

### DISCUSSION THREAD

**Discussion by hanuxxx** [swar/Swar-Chia-Plot-Manager#164] [Q&A]
> destination_directory - Can be a single value or a list of values.

What should I type as a list?

like this?

```
temporary_directory: D:\cache\Chia
D:\cache\Chia2

**Comment by selop** [comment]
You have to use the YAML syntax (use something like http://www.yamllint.com/ to verify).

The proper syntax for a list is:

```
temporary_directory: 
  - D:\cache\Chia
  - D:\cache\Chia2
```

**Reply by hanuxxx** [reply]
It strated successfully.

> python manager.py start

```Plot Manager has started...```

But when I type

> python manager.py view

```
Traceback (most recent call last):
  File "manager.py", line 36, in <module>
    view()
  File "C:\Chia\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 80, in view
    drive = job.temporary_directory.split('\\')[0]
AttributeError: 'list' object has no attribute 'split'
```

plot didn't start.

**Reply by hanuxxx** [reply]
```
  - name: D
    max_plots: 999
    farmer_public_key: a3becd0f1c10012a769295002d7ce52ea36a85bf5fd6d3d4918a55d58486dcf4330288a980141cac99895348fd4ee7d4
    pool_public_key: 8fc0a6b25b804eaf2108aa90246bcf8e9ed53ffdd85dd5b73bf8ff90d200d38b431b3c6b00f851f0e8e8b01efe3b6482
    temporary_directory:
            - D:\cache\Chia
            - D:\cache\Chia02
            - D:\cache\Chia03
    temporary2_directory:
    destination_directory: D:\Chia2
    size: 32
    bitfield: true
    threads: 2
    buckets: 64
    memory_buffer: 6000
    max_concurrent: 2
    max_concurrent_with_start_early: 3
    stagger_minutes: 60
    max_for_phase_1: 1
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false

```
