### DISCUSSION TITLE
Unable to run

### DISCUSSION THREAD

**Discussion by mutoo185** [swar/Swar-Chia-Plot-Manager#194] [Q&A]
windows2012
python3.7.10

(venv) C:\PerfLogs\Swar>pip install -r requirements.txt
Collecting dateparser==1.0.0
  Using cached dateparser-1.0.0-py2.py3-none-any.whl (279 kB)
Collecting discord_notify==1.0.0
  Using cached discord_notify-1.0.0-py3-none-any.whl (4.3 kB)
Collecting playsound==1.2.2
  Using cached playsound-1.2.2-py2.py3-none-any.whl (6.0 kB)
Collecting psutil==5.8.0
  Downloading psutil-5.8.0-cp37-cp37m-win_amd64.whl (244 kB)
     |█████████████▌                  | 102 kB 409 kB/s eta 0:00:0
     |███████████████                 | 112 kB 409 kB/s eta 0:00:
     |████████████████                | 122 kB 409 kB/s eta 0:00
     |█████████████████▌              | 133 kB 409 kB/s eta 0:
     |███████████████████             | 143 kB 409 kB/s eta 0
     |████████████████████            | 153 kB 409 kB/s eta
     |█████████████████████▌          | 163 kB 409 kB/s et
     |███████████████████████         | 174 kB 409 kB/s e
     |████████████████████████        | 184 kB 409 kB/s
     |█████████████████████████▌      | 194 kB 409 kB/
     |███████████████████████████     | 204 kB 409 kB
     |████████████████████████████    | 215 kB 409 k
     |█████████████████████████████▌  | 225 kB 409
     |███████████████████████████████ | 235 kB 40
     |████████████████████████████████| 244 kB 4
09 kB/s
Collecting python_pushover==0.4
  Using cached python-pushover-0.4.tar.gz (19 kB)
Collecting PyYAML==5.4.1
  Downloading PyYAML-5.4.1-cp37-cp37m-win_amd64.whl (210 kB)
     |██████████████                  | 92 kB 2.9 MB/s eta 0:00:01
     |███████████████▌                | 102 kB 2.2 MB/s eta 0:00
     |█████████████████               | 112 kB 2.2 MB/s eta 0:0
     |███████████████████             | 122 kB 2.2 MB/s eta 0
     |████████████████████            | 133 kB 2.2 MB/s eta
     |██████████████████████          | 143 kB 2.2 MB/s et
     |███████████████████████▌        | 153 kB 2.2 MB/s
     |█████████████████████████       | 163 kB 2.2 MB/s
     |██████████████████████████▌     | 174 kB 2.2 MB
     |████████████████████████████    | 184 kB 2.2 M
     |█████████████████████████████▌  | 194 kB 2.2
     |███████████████████████████████ | 204 kB 2.
     |████████████████████████████████| 210 kB 2
.2 MB/s
Collecting python-dateutil
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting regex!=2019.02.19
  Downloading regex-2021.4.4-cp37-cp37m-win_amd64.whl (269 kB)
     |█████████████▌                  | 112 kB 6.4 MB/s eta 0:00:0
     |██████████████▌                 | 122 kB 6.4 MB/s eta 0:00:
     |████████████████                | 133 kB 6.4 MB/s eta 0:00
     |█████████████████               | 143 kB 6.4 MB/s eta 0:0
     |██████████████████              | 153 kB 6.4 MB/s eta 0:
     |███████████████████▌            | 163 kB 6.4 MB/s eta
     |████████████████████▌           | 174 kB 6.4 MB/s eta
     |██████████████████████          | 184 kB 6.4 MB/s et
     |███████████████████████         | 194 kB 6.4 MB/s e
     |████████████████████████        | 204 kB 6.4 MB/s
     |█████████████████████████▌      | 215 kB 6.4 MB/
     |███████████████████████████     | 225 kB 6.4 MB
     |████████████████████████████    | 235 kB 6.4 M
     |█████████████████████████████   | 245 kB 6.4
     |██████████████████████████████▌ | 256 kB 6.
     |███████████████████████████████▌| 266 kB 6
     |████████████████████████████████| 269 kB 6
.4 MB/s
Collecting pytz
  Using cached pytz-2021.1-py2.py3-none-any.whl (510 kB)
Collecting tzlocal
  Using cached tzlocal-2.1-py2.py3-none-any.whl (16 kB)
Collecting requests>=1.0
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
Using legacy setup.py install for python-pushover, since package 'wheel' is not
installed.
Installing collected packages: six, python-dateutil, regex, pytz, tzlocal, datep
arser, discord-notify, playsound, psutil, certifi, chardet, idna, urllib3, reque
sts, python-pushover, PyYAML
    Running setup.py install for python-pushover ... done
Successfully installed PyYAML-5.4.1 certifi-2020.12.5 chardet-4.0.0 dateparser-1
.0.0 discord-notify-1.0.0 idna-2.10 playsound-1.2.2 psutil-5.8.0 python-dateutil
-2.8.1 python-pushover-0.4 pytz-2021.1 regex-2021.4.4 requests-2.25.1 six-1.16.0
 tzlocal-2.1 urllib3-1.26.4
WARNING: You are using pip version 20.1.1; however, version 21.1.1 is available.

You should consider upgrading via the 'c:\perflogs\swar\venv\scripts\python.exe
-m pip install --upgrade pip' command.

(venv) C:\PerfLogs\Swar>c:\perflogs\swar\venv\scripts\python.exe -m pip install
--upgrade pip
Collecting pip
  Downloading pip-21.1.1-py3-none-any.whl (1.5 MB)
     |████████████▌                   | 604 kB 467 kB/s eta 0:00:03
     |█████████████                   | 614 kB 467 kB/s eta 0:00:02
     |█████████████                   | 624 kB 467 kB/s eta 0:00:02
     |█████████████                   | 634 kB 467 kB/s eta 0:00:02
     |█████████████▌                  | 645 kB 467 kB/s eta 0:00:0
     |█████████████▌                  | 655 kB 467 kB/s eta 0:00:0
     |██████████████                  | 665 kB 467 kB/s eta 0:00:0
     |██████████████                  | 675 kB 467 kB/s eta 0:00:0
     |██████████████                  | 686 kB 467 kB/s eta 0:00:0
     |██████████████▌                 | 696 kB 467 kB/s eta 0:00:
     |██████████████▌                 | 706 kB 467 kB/s eta 0:00:
     |███████████████                 | 716 kB 467 kB/s eta 0:00:
     |███████████████                 | 727 kB 467 kB/s eta 0:00:
     |███████████████                 | 737 kB 467 kB/s eta 0:00:
     |███████████████▌                | 747 kB 467 kB/s eta 0:00
     |████████████████                | 757 kB 467 kB/s eta 0:00
     |████████████████                | 768 kB 467 kB/s eta 0:00
     |████████████████                | 778 kB 467 kB/s eta 0:00
     |████████████████                | 788 kB 467 kB/s eta 0:00
     |████████████████▌               | 798 kB 467 kB/s eta 0:0
     |█████████████████               | 808 kB 467 kB/s eta 0:0
     |█████████████████               | 819 kB 467 kB/s eta 0:0
     |█████████████████               | 829 kB 467 kB/s eta 0:0
     |█████████████████▌              | 839 kB 467 kB/s eta 0:
     |█████████████████▌              | 849 kB 467 kB/s eta 0:
     |██████████████████              | 860 kB 467 kB/s eta 0:
     |██████████████████              | 870 kB 467 kB/s eta 0:
     |██████████████████              | 880 kB 467 kB/s eta 0:
     |██████████████████▌             | 890 kB 467 kB/s eta 0
     |██████████████████▌             | 901 kB 467 kB/s eta 0
     |███████████████████             | 911 kB 467 kB/s eta 0
     |███████████████████             | 921 kB 467 kB/s eta 0
     |███████████████████             | 931 kB 467 kB/s eta 0
     |███████████████████▌            | 942 kB 467 kB/s eta
     |████████████████████            | 952 kB 467 kB/s eta
     |████████████████████            | 962 kB 467 kB/s eta
     |████████████████████            | 972 kB 467 kB/s eta
     |████████████████████            | 983 kB 467 kB/s eta
     |████████████████████▌           | 993 kB 467 kB/s eta
     |█████████████████████           | 1.0 MB 467 kB/s eta
     |█████████████████████           | 1.0 MB 467 kB/s eta
     |█████████████████████           | 1.0 MB 467 kB/s eta
     |█████████████████████▌          | 1.0 MB 467 kB/s et
     |█████████████████████▌          | 1.0 MB 467 kB/s et
     |██████████████████████          | 1.1 MB 467 kB/s et
     |██████████████████████          | 1.1 MB 467 kB/s et
     |██████████████████████          | 1.1 MB 467 kB/s et
     |██████████████████████▌         | 1.1 MB 467 kB/s e
     |██████████████████████▌         | 1.1 MB 467 kB/s e
     |███████████████████████         | 1.1 MB 467 kB/s e
     |███████████████████████         | 1.1 MB 467 kB/s e
     |███████████████████████         | 1.1 MB 467 kB/s e
     |███████████████████████▌        | 1.1 MB 467 kB/s
     |████████████████████████        | 1.1 MB 467 kB/s
     |████████████████████████        | 1.2 MB 467 kB/s
     |████████████████████████        | 1.2 MB 467 kB/s
     |████████████████████████▌       | 1.2 MB 467 kB/s
     |████████████████████████▌       | 1.2 MB 467 kB/s
     |█████████████████████████       | 1.2 MB 467 kB/s
     |█████████████████████████       | 1.2 MB 467 kB/s
     |█████████████████████████       | 1.2 MB 467 kB/s
     |█████████████████████████▌      | 1.2 MB 467 kB/
     |█████████████████████████▌      | 1.2 MB 467 kB/
     |██████████████████████████      | 1.2 MB 467 kB/
     |██████████████████████████      | 1.3 MB 467 kB/
     |██████████████████████████      | 1.3 MB 467 kB/
     |██████████████████████████▌     | 1.3 MB 467 kB
     |███████████████████████████     | 1.3 MB 467 kB
     |███████████████████████████     | 1.3 MB 467 kB
     |███████████████████████████     | 1.3 MB 467 kB
     |███████████████████████████     | 1.3 MB 467 kB
     |███████████████████████████▌    | 1.3 MB 467 k
     |████████████████████████████    | 1.3 MB 467 k
     |████████████████████████████    | 1.4 MB 467 k
     |████████████████████████████    | 1.4 MB 467 k
     |████████████████████████████▌   | 1.4 MB 467
     |████████████████████████████▌   | 1.4 MB 467
     |█████████████████████████████   | 1.4 MB 467
     |█████████████████████████████   | 1.4 MB 467
     |█████████████████████████████   | 1.4 MB 467
     |█████████████████████████████▌  | 1.4 MB 467
     |█████████████████████████████▌  | 1.4 MB 467
     |██████████████████████████████  | 1.4 MB 467
     |██████████████████████████████  | 1.5 MB 467
     |██████████████████████████████  | 1.5 MB 467
     |██████████████████████████████▌ | 1.5 MB 46
     |███████████████████████████████ | 1.5 MB 46
     |███████████████████████████████ | 1.5 MB 46
     |███████████████████████████████ | 1.5 MB 46
     |███████████████████████████████▌| 1.5 MB 4
     |███████████████████████████████▌| 1.5 MB 4
     |████████████████████████████████| 1.5 MB 4
     |████████████████████████████████| 1.5 MB 4
     |████████████████████████████████| 1.5 MB 4
67 kB/s
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.1.1
    Uninstalling pip-20.1.1:
      Successfully uninstalled pip-20.1.1
Successfully installed pip-21.1.1

(venv) C:\PerfLogs\Swar>pip install -r requirements.txt
Requirement already satisfied: dateparser==1.0.0 in c:\perflogs\swar\venv\lib\si
te-packages (from -r requirements.txt (line 1)) (1.0.0)
Requirement already satisfied: discord_notify==1.0.0 in c:\perflogs\swar\venv\li
b\site-packages (from -r requirements.txt (line 2)) (1.0.0)
Requirement already satisfied: playsound==1.2.2 in c:\perflogs\swar\venv\lib\sit
e-packages (from -r requirements.txt (line 3)) (1.2.2)
Requirement already satisfied: psutil==5.8.0 in c:\perflogs\swar\venv\lib\site-p
ackages (from -r requirements.txt (line 4)) (5.8.0)
Requirement already satisfied: python_pushover==0.4 in c:\perflogs\swar\venv\lib
\site-packages (from -r requirements.txt (line 5)) (0.4)
Requirement already satisfied: PyYAML==5.4.1 in c:\perflogs\swar\venv\lib\site-p
ackages (from -r requirements.txt (line 6)) (5.4.1)
Requirement already satisfied: pytz in c:\perflogs\swar\venv\lib\site-packages (
from dateparser==1.0.0->-r requirements.txt (line 1)) (2021.1)
Requirement already satisfied: python-dateutil in c:\perflogs\swar\venv\lib\site
-packages (from dateparser==1.0.0->-r requirements.txt (line 1)) (2.8.1)
Requirement already satisfied: tzlocal in c:\perflogs\swar\venv\lib\site-package
s (from dateparser==1.0.0->-r requirements.txt (line 1)) (2.1)
Requirement already satisfied: regex!=2019.02.19 in c:\perflogs\swar\venv\lib\si
te-packages (from dateparser==1.0.0->-r requirements.txt (line 1)) (2021.4.4)
Requirement already satisfied: requests>=1.0 in c:\perflogs\swar\venv\lib\site-p
ackages (from python_pushover==0.4->-r requirements.txt (line 5)) (2.25.1)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\perflogs\swar\venv\lib\si
te-packages (from requests>=1.0->python_pushover==0.4->-r requirements.txt (line
 5)) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\perflogs\swar\venv\lib\s
ite-packages (from requests>=1.0->python_pushover==0.4->-r requirements.txt (lin
e 5)) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in c:\perflogs\swar\venv\lib\site-pa
ckages (from requests>=1.0->python_pushover==0.4->-r requirements.txt (line 5))
(2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\perflogs\swar\venv\li
b\site-packages (from requests>=1.0->python_pushover==0.4->-r requirements.txt (
line 5)) (1.26.4)
Requirement already satisfied: six>=1.5 in c:\perflogs\swar\venv\lib\site-packag
es (from python-dateutil->dateparser==1.0.0->-r requirements.txt (line 1)) (1.16
.0)

(venv) C:\PerfLogs\Swar>python manager.py start
Traceback (most recent call last):
  File "manager.py", line 29, in <module>
    start_manager()
  File "C:\PerfLogs\Swar\plotmanager\library\utilities\commands.py", line 20, in
 start_manager
    if get_manager_processes():
  File "C:\PerfLogs\Swar\plotmanager\library\utilities\processes.py", line 28, i
n get_manager_processes
    for process in psutil.process_iter():
  File "C:\PerfLogs\Swar\venv\lib\site-packages\psutil\__init__.py", line 1439,
in process_iter
    yield add(pid)
  File "C:\PerfLogs\Swar\venv\lib\site-packages\psutil\__init__.py", line 1414,
in add
    proc = Process(pid)
  File "C:\PerfLogs\Swar\venv\lib\site-packages\psutil\__init__.py", line 326, i
n __init__
    self._init(pid)
  File "C:\PerfLogs\Swar\venv\lib\site-packages\psutil\__init__.py", line 354, i
n _init
    self.create_time()
  File "C:\PerfLogs\Swar\venv\lib\site-packages\psutil\__init__.py", line 710, i
n create_time
    self._create_time = self._proc.create_time()
  File "C:\PerfLogs\Swar\venv\lib\site-packages\psutil\_pswindows.py", line 681,
 in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
  File "C:\PerfLogs\Swar\venv\lib\site-packages\psutil\_pswindows.py", line 671,
 in convert_oserror
    raise exc
  File "C:\PerfLogs\Swar\venv\lib\site-packages\psutil\_pswindows.py", line 679,
 in wrapper
    return fun(self, *args, **kwargs)
  File "C:\PerfLogs\Swar\venv\lib\site-packages\psutil\_pswindows.py", line 933,
 in create_time
    user, system, created = cext.proc_times(self.pid)
OSError: [WinError 0] The operation completed successfully: '(originated from Op
enProcess)'

(venv) C:\PerfLogs\Swar>

(venv) C:\PerfLogs\Swar>python manager.py view
Traceback (most recent call last):
  File "manager.py", line 36, in <module>
    view()
  File "C:\PerfLogs\Swar\plotmanager\library\utilities\commands.py", line 74, in
 view
    notification_settings, debug_level, view_settings = get_config_info()
  File "C:\PerfLogs\Swar\plotmanager\library\parse\configuration.py", line 111,
in get_config_info
    notification_settings = _get_notifications_settings(config=config)
  File "C:\PerfLogs\Swar\plotmanager\library\parse\configuration.py", line 74, i
n _get_notifications_settings
    _check_parameters(parameter=notifications, expected_parameters=expected_para
meters, parameter_type='notification')
  File "C:\PerfLogs\Swar\plotmanager\library\parse\configuration.py", line 97, i
n _check_parameters
    raise InvalidYAMLConfigException(f'Failed to find the following {parameter_t
ype} parameters: '
plotmanager.library.utilities.exceptions.InvalidYAMLConfigException: Failed to f
ind the following notification parameters: notify_discord, discord_webhook_url,
notify_sound, song

(venv) C:\PerfLogs\Swar>

config.yaml

```
# This is a single variable that should contain the location of your chia executable file. This is the blockchain executable.
#
# WINDOWS EXAMPLE: C:\Users\eva\AppData\Local\chia-blockchain\app-1.1.4\resources\app.asar.unpacked\daemon\chia.exe
#   LINUX EXAMPLE: /usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/chia
#  LINUX2 EXAMPLE: /home/swar/chia-blockchain/venv/bin/chia
chia_location: C:\Users\eva\AppData\Local\chia-blockchain\app-1.1.4\resources\app.asar.unpacked\daemon\chia.exe


manager:
  # These are the config settings that will only be used by the plot manager.
  #
  # check_interval: The number of seconds to wait before checking to see if a new job should start.
  #      log_level: Keep this on ERROR to only record when there are errors. Change this to INFO in order to see more
  #                 detailed logging. Warning: INFO will write a lot of information.
  check_interval: 60
  log_level: ERROR


log:
  # folder_path: This is the folder where your log files for plots will be saved.
  folder_path: C:\PerfLogs\1


view:
  # These are the settings that will be used by the view.
  #
  #            check_interval: The number of seconds to wait before updating the view.
  #           datetime_format: The datetime format that you want displayed in the view. See here
  #                            for formatting: https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes
  # include_seconds_for_phase: This dictates whether seconds are included in the phase times.
  #        include_drive_info: This dictates whether the drive information will be showed.
  #               include_cpu: This dictates whether the CPU information will be showed.
  #               include_ram: This dictates whether the RAM information will be showed.
  #        include_plot_stats: This dictates whether the plot stats will be showed.
  check_interval: 60
  datetime_format: "%Y-%m-%d %H:%M:%S"
  include_seconds_for_phase: false
  include_drive_info: true
  include_cpu: true
  include_ram: true
  include_plot_stats: true


notifications:
  # These are different settings in order to notified when the plot manager starts and when a plot has been completed.

  # DISCORD
  #notify_discord: false
  #discord_webhook_url: https://discord.com/api/webhooks/0000000000000000/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  # PLAY AUDIO SOUND
  #notify_sound: false
  #song: audio.mp3

  # PUSHOVER PUSH SERVICE
  notify_pushover: false
  pushover_user_key: xx
  pushover_api_key: xx
  
  # TWILIO
  notify_twilio: false
  twilio_account_sid: xxxxx
  twilio_auth_token: xxxxx
  twilio_from_phone: +1234657890
  twilio_to_phone: +1234657890


progress:
  # phase_line_end: These are the settings that will be used to dictate when a phase ends in the progress bar. It is
  #                 supposed to reflect the line at which the phase will end so the progress calculations can use that
  #                 information with the existing log file to calculate a progress percent.
  #   phase_weight: These are the weight to assign to each phase in the progress calculations. Typically, Phase 1 and 3
  #                 are the longest phases so they will hold more weight than the others.
  phase1_line_end: 801
  phase2_line_end: 834
  phase3_line_end: 2474
  phase4_line_end: 2620
  phase1_weight: 33.4
  phase2_weight: 20.43
  phase3_weight: 42.29
  phase4_weight: 3.88


global:
  # These are the settings that will be used globally by the plot manager.
  #
  # max_concurrent: The maximum number of plots that your system can run. The manager will not kick off more than this
  #                 number of plots total over time.
  max_concurrent: 10


jobs:
  # These are the settings that will be used by each job. Please note you can have multiple jobs and each job should be
  # in YAML format in order for it to be interpreted correctly. Almost all the values here will be passed into the
  # Chia executable file.
  #
  # Check for more details on the Chia CLI here: https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference
  #
  # name: This is the name that you want to give to the job.
  # max_plots: This is the maximum number of jobs to make in one run of the manager. Any restarts to manager will reset
  #            this variable. It is only here to help with short term plotting.
  #
  # [OPTIONAL] farmer_public_key: Your farmer public key. If none is provided, it will not pass in this variable to the
  #                               chia executable which results in your default keys being used. This is only needed if
  #                               you have chia set up on a machine that does not have your credentials.
  # [OPTIONAL] pool_public_key: Your pool public key. Same information as the above.
  #
  # temporary_directory: Only a single directory should be passed into here. This is where the plotting will take place.
  # [OPTIONAL] temporary2_directory: Can be a single value or a list of values. This is an optional parameter to use in
  #                                  case you want to use the temporary2 directory functionality of Chia plotting.
  # destination_directory: Can be a single value or a list of values. This is the final directory where the plot will be
  #                        transferred once it is completed. If you provide a list, it will cycle through each drive
  #                        one by one.
  #
  # size: This refers to the k size of the plot. You would type in something like 32, 33, 34, 35... in here.
  # bitfield: This refers to whether you want to use bitfield or not in your plotting. Typically, you want to keep
  #           this as true.
  # threads: This is the number of threads that will be assigned to the plotter. Only phase 1 uses more than 1 thread.
  # buckets: The number of buckets to use. The default provided by Chia is 128.
  # memory_buffer: The amount of memory you want to allocate to the process.
  # max_concurrent: The maximum number of plots to have for this job at any given time.
  # max_concurrent_with_start_early: The maximum number of plots to have for this job at any given time including
  #                                  phases that started early.
  # stagger_minutes: The amount of minutes to wait before the next job can get kicked off. You can even set this to
  #                  zero if you want your plots to get kicked off immediately when the concurrent limits allow for it.
  # max_for_phase_1: The maximum number of plots on phase 1 for this job.
  # concurrency_start_early_phase: The phase in which you want to start a plot early. It is recommended to use 4 for
  #                                this field.
  # concurrency_start_early_phase_delay: The maximum number of seconds to wait before a new plot gets kicked off when
  #                                      the start early phase has been detected.
  # temporary2_destination_sync: This field will always submit the destination directory as the temporary2 directory.
  #                              These two directories will be in sync so that they will always be submitted as the
  #                              same value.
  - name: test
    max_plots: 999
    farmer_public_key:
    pool_public_key:
    temporary_directory: E:\test
    destination_directory: D:\test
    size: 32
    bitfield: true
    threads: 4
    buckets: 128
    memory_buffer: 5000
    max_concurrent: 6
    max_concurrent_with_start_early: 7
    stagger_minutes: 60
    max_for_phase_1: 2
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false

```
