### DISCUSSION TITLE
Trying to understand how stagger_minutes works with concurrency_start_early_phase and concurrency_start_early_phase_delay

### DISCUSSION THREAD

**Discussion by zeroarst** [swar/Swar-Chia-Plot-Manager#248] [Q&A]
```
  - name: default
    max_plots: 999
    farmer_public_key:
    pool_public_key:
    temporary_directory: E:\chia-plotter
    temporary2_directory:
    destination_directory: F:\chia\farming
    size: 32
    bitfield: true
    threads: 4
    buckets: 64
    memory_buffer: 7000
    max_concurrent: 1
    max_concurrent_with_start_early: 2
    stagger_minutes: 60
    max_for_phase_1: 1
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false
```
Dose above mean, it will start 1 plot (let's call p1), then wait for `stagger_minutes` (60mins), and once p1's phase 4 kicked off, it then wait for `concurrency_start_early_phase_delay` (0mins) time to kick off p2?

What if `concurrency_start_early_phase` started before `stagger_minutes` (60mins), dose it start p2 straightway or still wait for `stagger_minutes`?
