### DISCUSSION TITLE
Help with optimizing config. 5950x 64GB 2x2TB Gen4

### DISCUSSION THREAD

**Discussion by LazarusDarkside** [swar/Swar-Chia-Plot-Manager#704] [Q&A]
Hello,
My setup as below;
Cpu: Ryzen 9 5950x
Ram: 4x16GB
Mobo: Msi X570 Unify
Nvme: 2x2tb Gen4 (Samsung 980 Pro & Corsair MP600 Pro) 

Do i need to raid my 2 different ssd's? Soon i will get 1 more each. Will it be better to raid them when they are pair? Also could you help me about settings?

**Comment by AlexG79** [comment]
No RAID.

**Reply by bfasan** [reply]
raid 0 would make a big difference i think (especially might as well since they're matching drives

**Reply by creamsoup** [reply]
> raid 0 would make a big difference i think (especially might as well since they're matching drives

sorry, definitely no. there are plenty of benchmark result for this. I also personally tested it. think about what makes plotting faster.

**Comment by LazarusDarkside** [comment]
I am trying now as seperated drives.
20 plot parallel 10 for each. 6 phase-1 3 for each. I will try 4 phase-1 on each soon. Then i will go on raid 0 with 2 totally same ssd to see the difference.

**Reply by creamsoup** [reply]
raid0 is bad. not worth to give a shot. why do you think it will help? because it helps large file transfer? other than large file transfer, ssd raid0 slows down.
for the reference, my 5950x generates 47 plots a day without much optimization.

**Reply by g0ze21** [reply]
Oh wow, could you share your config?

My specs
AMD Ryzen 9 5900X 12-Core
64 GB RAM
1 NVMe x 2TB Gen4
1 NVMe x 1TB Gen4 
1 NVMe x 2TB Gen3

I just can make about 18 plots per day.

My config

- name: CRUCIAL2T
    max_plots: 80
    farmer_public_key:
    pool_public_key:
    temporary_directory: D:\
    temporary2_directory:
    destination_directory:
    - G:\GREEN4T1
    - H:\PURPLE10T2
    - I:\PURPLE10T1
    size: 32
    bitfield: true
    threads: 8
    buckets: 128
    memory_buffer: 3408
    max_concurrent: 3
    max_concurrent_with_start_early: 5
    initial_delay_minutes: 0
    stagger_minutes: 60
    max_for_phase_1: 3
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false
    exclude_final_directory: true
    skip_full_destinations: true
    unix_process_priority: 10
    windows_process_priority: 256
    enable_cpu_affinity: false
    cpu_affinity: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23 ]

**Reply by creamsoup** [reply]
sure.
i have 3 2TB ssd drives on linux using ext4.

```
  - name: chiaTemp1
    max_plots: 999
    farmer_public_key:
    pool_public_key:
    temporary_directory: /mnt/chiaTemp1
    temporary2_directory:
    destination_directory: /mnt/chiaFinal6
    size: 32
    bitfield: true
    threads: 4
    buckets: 128
    memory_buffer: 4000
    max_concurrent: 6
    max_concurrent_with_start_early: 7
    stagger_minutes: 30
    max_for_phase_1: 3
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false
    exclude_final_directory: false
    skip_full_destinations: true
    unix_process_priority: 10
    windows_process_priority: 32
    enable_cpu_affinity: false
    cpu_affinity: [ 0, 1, 2, 3, 4, 5 ]
    initial_delay_minutes: 0
```

use more than 4 threads is wasting of energy

**Reply by g0ze21** [reply]
thx bro!

**Reply by LazarusDarkside** [reply]
All 3 using same config?

**Reply by creamsoup** [reply]
> All 3 using same config?

yes other than temp/dest directory.

**Reply by creamsoup** [reply]
for the record, i think increasing stagger minutes can be helpful. but i don't have enough time to tinker with it yet.

**Reply by LazarusDarkside** [reply]
@creamsoup How many plots a day you are getting a day with abow settings?

**Reply by LazarusDarkside** [reply]
And how about your general settings?
minimum_minutes_between_jobs: ?

**Reply by creamsoup** [reply]
i am getting 47 consistently. (3 2TB ssds). minimum_minutes_between_jobs = 0. max concurrent is 18, max_for_phase_1 is 7 but those numbers are just out of my hunch.

**Reply by eongor** [reply]
Hi Creamsoup,

thank you very much for sharing your config, Could you help us for the config for RYZEN5900X and 2TB NVME (samsung 980 pro)?

appreciated !

**Reply by creamsoup** [reply]
@eongor, I would start from following numbers. but this is guestimated, tweak based on the result. you should aim for 60%ish CPU utilization. 100% io utilization. 

1SSD:
```yaml
max_concurrent: 7
max_for_phase_1: 3
threads: 4
stagger_minutes: 45
```

2SSDs: 2 sets of
```yaml
max_concurrent: 6 
max_for_phase_1: 3 # or 2
threads: 3 # or 2
stagger_minutes: 60
```
