### DISCUSSION TITLE
Xeon E5-2689, 2x1TB NVME config, 32GB RAM

### DISCUSSION THREAD

**Discussion by DimitriBalder** [swar/Swar-Chia-Plot-Manager#982] [Q&A]
Hi Guys, i have Xeon E5-2689, 2x1TB NVME config, 32GB RAM. Can you help with a better config? 
Config at the moment:
```
- name: SSD_1
    max_plots: 999
    farmer_public_key:
    pool_public_key:
    temporary_directory: D:\Plotter
    temporary2_directory:
    destination_directory: H:\
    size: 32
    bitfield: true
    threads: 8
    buckets: 128
    memory_buffer: 4200
    max_concurrent: 40
    max_concurrent_with_start_early: 40
    initial_delay_minutes: 0
    stagger_minutes: 1
    max_for_phase_1: 1
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false
    exclude_final_directory: false
    skip_full_destinations: true
    unix_process_priority: 10
    windows_process_priority: 32
    enable_cpu_affinity: true
    cpu_affinity: [ 0, 1, 2, 3, 4, 5, 6, 7 ]

  - name: SSD_2
    max_plots: 999
    farmer_public_key:
    pool_public_key:
    temporary_directory: G:\Plotter
    temporary2_directory:
    destination_directory: J:\
    size: 32
    bitfield: true
    threads: 8
    buckets: 128
    memory_buffer: 4200
    max_concurrent: 40
    max_concurrent_with_start_early: 40
    initial_delay_minutes: 0
    stagger_minutes: 1
    max_for_phase_1: 1
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false
    exclude_final_directory: false
    skip_full_destinations: true
    unix_process_priority: 10
    windows_process_priority: 32
    enable_cpu_affinity: true
    cpu_affinity: [ 8, 9, 10, 11, 12, 13, 14, 15 ]
    ```
