### ISSUE TITLE
Plotmanager not initiating plotting "No keys"

### ISSUE THREAD

**Issue by forReason** [swar/Swar-Chia-Plot-Manager#1025]
So, The plot manager was running fine before. Im using the latest release version.

It starts up fine and apparently tries to initiate new jobs for plotting. 
I changed the config though from staggering 0 to staggering 180.

Plotter log says it could not obtain keys:
```[6100] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 57, in create_plots
  File "chia\plotting\create_plots.py", line 30, in get_farmer_public_key
RuntimeError: No keys, please run 'chia keys add', 'chia keys generate' or provide a public key with -f
```

I am plotting on a fully sychronized chia node so as far as I know no keys should be required.

config:
```
chia_location: C:\Users\julia\AppData\Local\chia-blockchain\app-1.1.6\resources\app.asar.unpacked\daemon\chia.exe


manager:
  check_interval: 15
  log_level: ERROR


log:
  # folder_path: This is the folder where your log files for plots will be saved.
  folder_path: F:\logs\Plotter


view:
  check_interval: 15
  datetime_format: "%Y-%m-%d %H:%M:%S"
  include_seconds_for_phase: false
  include_drive_info: true
  include_cpu: true
  include_ram: true
  include_plot_stats: true


notifications:
  # These are different settings in order to notified when the plot manager starts and when a plot has been completed.

  # DISCORD
  notify_discord: false
  discord_webhook_url: https://discord.com/api/webhooks/0000000000000000/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  # IFTTT, ref https://ifttt.com/maker_webhooks, and this function will send title as value1 and message as value2.
  notify_ifttt: false
  ifttt_webhook_url: https://maker.ifttt.com/trigger/{event}/with/key/{api_key}

  # PLAY AUDIO SOUND
  notify_sound: false
  song: audio.mp3

  # PUSHOVER PUSH SERVICE
  notify_pushover: false
  pushover_user_key: xx
  pushover_api_key: xx
  
  # TELEGRAM
  notify_telegram: false
  telegram_token: xxxxx

  # TWILIO
  notify_twilio: false
  twilio_account_sid: xxxxx
  twilio_auth_token: xxxxx
  twilio_from_phone: +1234657890
  twilio_to_phone: +1234657890


instrumentation:
  prometheus_enabled: false
  prometheus_port: 9090


progress:
  phase1_line_end: 801
  phase2_line_end: 834
  phase3_line_end: 2474
  phase4_line_end: 2626
  phase1_weight: 39.62
  phase2_weight: 16.57
  phase3_weight: 34.97
  phase4_weight: 8.84


global:
  max_concurrent: 4
  max_for_phase_1: 2
  minimum_minutes_between_jobs: 0


jobs:
  - name: Plotfield1 (Drive F)
    max_plots: 999
    farmer_public_key:
    pool_public_key:
    temporary_directory: E:\temp_Plotfield1
    temporary2_directory: F:\temp
    destination_directory: F:\plots-single
    size: 32
    bitfield: true
    threads: 3
    buckets: 128
    memory_buffer: 4000
    max_concurrent: 3
    max_concurrent_with_start_early: 3
    initial_delay_minutes: 0
    stagger_minutes: 180
    max_for_phase_1: 1
    concurrency_start_early_phase: 3
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false
    exclude_final_directory: false
    skip_full_destinations: true
    unix_process_priority: 10
    windows_process_priority: 32
    enable_cpu_affinity: true
    cpu_affinity: [ 0, 1, 2, 3, 4, 5 ]

  - name: Plotfield2 (Drive G)
    max_plots: 999
    farmer_public_key:
    pool_public_key:
    temporary_directory: E:\temp_Plotfield2
    temporary2_directory: G:\temp
    destination_directory: G:\plots-single
    size: 32
    bitfield: true
    threads: 3
    buckets: 128
    memory_buffer: 4000
    max_concurrent: 3
    max_concurrent_with_start_early: 3
    initial_delay_minutes: 0
    stagger_minutes: 180
    max_for_phase_1: 1
    concurrency_start_early_phase: 3
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false
    exclude_final_directory: false
    skip_full_destinations: true
    unix_process_priority: 10
    windows_process_priority: 32
    enable_cpu_affinity: true
    cpu_affinity: [ 0, 1, 2, 3, 4, 5 ]
```
