### ISSUE TITLE
percentage show wrong if setting bucket 64 

### ISSUE THREAD

**Issue by jimkangosjarvi** [swar/Swar-Chia-Plot-Manager#1085]
Job is done at 66% :D

**Comment by creamsoup** [comment]
and it finishes at 100% if bucket size is 128?

**Comment by jimkangosjarvi** [comment]
No at 66%. It is done Br jimSent from my Galaxy
-------- Original message --------From: Jihun Cho ***@***.***> Date: 6/3/21  04:04  (GMT+02:00) To: swar/Swar-Chia-Plot-Manager ***@***.***> Cc: jimkangosjarvi ***@***.***>, Author ***@***.***> Subject: Re: [swar/Swar-Chia-Plot-Manager] percentage show wrong if setting bucket 64  (#1085) 
and it finishes at 100% if bucket size is 128?

**Comment by creamsoup** [comment]
with current swar's implementation that means your log is corrupted or your config value for `progress` is wrong. could be both. as long as it reaches stage 4, it should be `sum(phase_weight)` which is 90+% unless the config is modified.

you can modify `progress` accordingly.

```yaml
progress:
  # phase_line_end: These are the settings that will be used to dictate when a phase ends in the progress bar. It is
  #                 supposed to reflect the line at which the phase will end so the progress calculations can use that
  #                 information with the existing log file to calculate a progress percent.
  #   phase_weight: These are the weight to assign to each phase in the progress calculations. Typically, Phase 1 and 3
  #                 are the longest phases so they will hold more weight than the others.
  phase1_line_end: 801
  phase2_line_end: 834
  phase3_line_end: 2474
  phase4_line_end: 2620
  phase1_weight: 33.4
  phase2_weight: 20.43
  phase3_weight: 42.29
  phase4_weight: 3.88
```
