### ISSUE TITLE
Limited to 10 concurrent jobs

### ISSUE THREAD

**Issue by lfarrand** [swar/Swar-Chia-Plot-Manager#245]
Hi there,

First of all, thanks very much for all of the effort you've put into building this. I'm sure it's taken quite some time to get to this point!

I've noticed that regardless of the number that I provide to the max_* config fields, the manager only starts 10 jobs in total.

![image](https://user-images.githubusercontent.com/1841445/117926172-3e2d8d80-b2f0-11eb-8387-cef41a446b40.png)

My configuration is:

```
  - name: job1
    max_plots: 9999
    farmer_public_key: <snip>
    pool_public_key: <snip>
    temporary_directory: G:\chia\temp
    temporary2_directory: H:\chia\temp
    destination_directory:
      - P:\chia\plots
      - Q:\chia\plots
    size: 32
    bitfield: true
    threads: 4
    buckets: 128
    memory_buffer: 3408
    max_concurrent: 26
    max_concurrent_with_start_early: 32
    stagger_minutes: 7
    max_for_phase_1: 22
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false

```

Is this the expected behaviour? If not, how can I get it to run more than 10 jobs in parallel?

Many thanks,

Lee
