### ISSUE TITLE
'No module named plotter' error

### ISSUE THREAD

**Issue by sysadt** [swar/Swar-Chia-Plot-Manager#47]
**System:**
Fresh Win10 Install, 19042.928, fresh python 3.9 install

**Error:**
```
C:\Temp\Swar-Chia-Plot-Manager-0.0.0b\plotter>python manager.py start
Traceback (most recent call last):
  File "C:\Temp\Swar-Chia-Plot-Manager-0.0.0b\plotter\manager.py", line 7, in <module>
    from parse.configuration import get_config_info
  File "C:\Temp\Swar-Chia-Plot-Manager-0.0.0b\plotter\parse\configuration.py", line 4, in <module>
    from plotter.utilities.exceptions import InvalidYAMLConfigException
ModuleNotFoundError: No module named 'plotter'
```

When running `python manager.py start` from the location stated in your guide:
`C:\Temp\Swar-Chia-Plot-Manager-0.0.0b>python manager.py start
python: can't open file 'C:\Temp\Swar-Chia-Plot-Manager-0.0.0b\manager.py': [Errno 2] No such file or directory`

**Config file:**
```
chia_location: C:\Users\username\AppData\Local\chia-blockchain\app-1.1.2\resources\app.asar.unpacked\daemon\chia

log_location:
  folder_path: C:\Logs\Plotter\swar.log
  check_seconds: 60

global:
  max_concurrent: 6

jobs:
  - name: CDrive
    max_plots: 999
    temporary_directory: C:\temp1
    destination_directory:
      - Z:\
    size: 32
    bitfield: true
    threads: 4
    buckets: 128
    memory_buffer: 3450
    max_concurrent: 3
    max_concurrent_with_disregard: 3
    stagger_minutes: 40
    max_for_phase_1: 1
    concurrency_disregard_phase: 4
    concurrency_disregard_phase_delay: 0

  - name: DDrive
    max_plots: 999
    temporary_directory: D:\temp2
    destination_directory:
      - Z:\
    size: 32
    bitfield: true
    threads: 4
    buckets: 128
    memory_buffer: 3450
    max_concurrent: 3
    max_concurrent_with_disregard: 3
    stagger_minutes: 40
    max_for_phase_1: 2
    concurrency_disregard_phase: 4
    concurrency_disregard_phase_delay: 0
```
How to proceed?
