### ISSUE TITLE
Only starting 1 concurrent job at a time

### ISSUE THREAD

**Issue by spartandigitalweb** [swar/Swar-Chia-Plot-Manager#691]
I updated to the latest version. I have the concurrent plots setting on the config file set to 6, but it only starts 1 at a time. Shouldn't it be starting all 6 simultaneously?

As a temporary fix, I set the stagger to be 25 minutes now so I can get 6 concurrent in Phase 1 (which takes me roughly 150 minutes to complete).

**Comment by JayPark777** [comment]
Would you like to explore the 'initial_delay_minutes' option? This should be '0'.

**Comment by vigohe** [comment]
same here.  

As a workaround I did create another job to run as "concurrently"

**Comment by spartandigitalweb** [comment]
I tried that but it said I can't run duplicate jobs to the same drive.

> same here.
> 
> As a workaround I did create another job to run as "concurrently"

**Comment by vigohe** [comment]
> I tried that but it said I can't run duplicate jobs to the same drive.
> 
> > same here.
> > As a workaround I did create another job to run as "concurrently"

But set the `temporary_directory` to another folder in the same drive like

```
  - name: Job-01
    max_plots: 2
    farmer_public_key:
    pool_public_key:
    temporary_directory: D:\Plotter-01
```

```
  - name: Job-01
    max_plots: 2
    farmer_public_key:
    pool_public_key:
    temporary_directory: D:\Plotter-02
```
