### ISSUE TITLE
Job stops plotting after first cycle

### ISSUE THREAD

**Issue by ReneVolution** [swar/Swar-Chia-Plot-Manager#70]
Hello 👋 ,

first of all: Thanks for this great piece of software and the effort you've put in. 

I am not sure if I misunderstand something fundamentally here, but given the following job configuration, I expected a different result and wonder why this is. 

So, with this config:

```yaml
jobs:
  - name: micron
    max_plots: 20
    farmer_public_key:
    pool_public_key:
    temporary_directory: /Users/xxxxxx/Documents/CHIA_TEMP
    temporary2_directory: /Users/xxxxx/Documents/CHIA_TEMP
    destination_directory: /Volumes/CHIA_PLOTS1
    size: 32
    bitfield: true
    threads: 4
    buckets: 128
    memory_buffer: 5000
    max_concurrent: 2
    max_concurrent_with_start_early: 3
    stagger_minutes: 0
    max_for_phase_1: 2
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false
```

I expected 2 plots (Plot 1 & 2) immediately to start and once at least one of the 2 reaches phase 4, to start another plot (Plot 3). Once either Plot 1 or Plot 2 finishes, I expected that to kick off another plot (Plot 4) and this to cycle until Plot 20 (given `max_plots: 20` in the config).

Now, the problem that I am running into is that Plot 4 never starts and after the first 3 plots, there is no more plots being created.

Is this the expected behaviour? 

Thanks. I appreciate any help.
