### ISSUE TITLE
plot creation takes 20hours!!

### ISSUE THREAD

**Issue by megaacheyounes** [swar/Swar-Chia-Plot-Manager#747]
Hi,

First, thank you for this amazing tool.

I tried to run it on my machine using chia 1.1.16 but plot creation is taking 20 hours +. I tried to play with the numbers in the config file to get better time but I didn't see much improvement, I would be thankful if any of you help me optimize the config files for my machine:

my pc specs:
```
    -Motherboard: ASUS B550-F
    - CPU: AMD Ryzen 7 3700x 8-core 16 CPU
    - RAM: 32 GB 2666 Mhz
    - STORAGE:
        - 128 GB SATA SSD ( for windows OS ): READ: 250 MB/S, WRITE: 500 MB/s
        - 2 TB NVME PCIe 3.0 x4 (temp drive for plotting D:/): READ:  2.3GB/s, WRITE: 2GB/s
        - 2 TB NVME PCIe 3.0 x4 (temp drive for plotting E:/): READ: 2.2GB/S, WRITE: 2GB/S
        - 4TB SATA HDD 5700RPM (dest drive for plots Z:/)
        - 10TB USB 3.0 HDD 5400 (des drive for plots F:/)
```
# my configuration:
        - name: 2TB_chia_1
            max_plots: 999
            farmer_public_key:
            pool_public_key:
            temporary_directory: D:\
            temporary2_directory:
            destination_directory: 
                -   Z:\
                -   F:\
            size: 32
            bitfield: true
            threads: 8
            buckets: 128
            memory_buffer: 4000
            max_concurrent: 4
            max_concurrent_with_start_early: 7
            stagger_minutes: 60
            max_for_phase_1: 2
            concurrency_start_early_phase: 4
            concurrency_start_early_phase_delay: 0
            temporary2_destination_sync: false
        
          - name: 2TB_chia_2
            max_plots: 999
            farmer_public_key:
            pool_public_key:
            temporary_directory: E:\
            temporary2_directory:
            destination_directory:
                -   Z:\
                -   F:\
            size: 32
            bitfield: true
            threads: 8
            buckets: 128
            memory_buffer: 4000
            max_concurrent: 4
            max_concurrent_with_start_early: 3
            stagger_minutes: 180
            max_for_phase_1: 1
            concurrency_start_early_phase: 4
            concurrency_start_early_phase_delay: 0
            temporary2_destination_sync: false

manager view:

![chia_system_1](https://user-images.githubusercontent.com/36759976/119230734-97868f80-bb2e-11eb-97c3-027de1d6550b.PNG)

please let me know if I can provide any other information to help optimize, THANK YOU!.
