### ISSUE TITLE
Cannot create more than 1 plot

### ISSUE THREAD

**Issue by revantjhalani** [swar/Swar-Chia-Plot-Manager#791]
If I start the manager by: 
 - either directly or first activating the chia venv and then starting up the manager as sudo leads to 1 or 2 plots starting and then this for all the subsequent plots: 
 `Traceback (most recent call last):
  File "/home/sotpurk/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/home/sotpurk/chia-blockchain/chia/cmds/chia.py", line 77, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/sotpurk/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sotpurk/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sotpurk/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sotpurk/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/home/sotpurk/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sotpurk/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sotpurk/chia-blockchain/venv/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sotpurk/chia-blockchain/chia/cmds/plots.py", line 34, in plots_cmd
    raise RuntimeError("Please initialize (or migrate) your config directory with 'chia init'")
RuntimeError: Please initialize (or migrate) your config directory with 'chia init'
` 
- Running as the user (no sudo), 
`Traceback (most recent call last):
  File "/home/sotpurk/chia-blockchain/venv/lib/python3.9/site-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/sotpurk/chia-blockchain/venv/lib/python3.9/site-packages/psutil/_pslinux.py", line 1992, in nice_set
    return cext_posix.setpriority(self.pid, value)
PermissionError: [Errno 13] Permission denied

    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/sotpurk/Swar-Chia-Plot-Manager-v.0.1.0/stateless-manager.py", line 94, in <module>
        jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
      File "/home/sotpurk/Swar-Chia-Plot-Manager-v.0.1.0/plotmanager/library/utilities/jobs.py", line 258, in monitor_jobs_to_start
        job, work = start_work(
      File "/home/sotpurk/Swar-Chia-Plot-Manager-v.0.1.0/plotmanager/library/utilities/jobs.py", line 327, in start_work
        psutil.Process(pid).nice(nice_val)
      File "/home/sotpurk/chia-blockchain/venv/lib/python3.9/site-packages/psutil/__init__.py", line 724, in nice
        self._proc.nice_set(value)
      File "/home/sotpurk/chia-blockchain/venv/lib/python3.9/site-packages/psutil/_pslinux.py", line 1578, in wrapper
        raise AccessDenied(self.pid, self._name)`

A solution I found somewhere was to run the program as the user that chia is installed for in the venv, but if I dont run it as root, the second error pops up in debug, and if I do, the first one. Not sure how to go about this

**Comment by tibbon** [comment]
I'm also not seeing more than one plot occur at a time, but I'm unclear if it's related to your issue. Nothing particular in the logs about it. I think I'm configured properly

```
chia_location: /home/tibbon/chia-blockchain/venv/bin/chia


manager:
  check_interval: 60
  log_level: ERROR


log:
  folder_path: /home/tibbon/chia-blockchain/logs


view:
  check_interval: 60
  datetime_format: "%Y-%m-%d %H:%M:%S"
  include_seconds_for_phase: false
  include_drive_info: true
  include_cpu: true
  include_ram: true
  include_plot_stats: true


# Removed notification config for Github

progress:
  phase1_line_end: 801
  phase2_line_end: 834
  phase3_line_end: 2474
  phase4_line_end: 2620
  phase1_weight: 33.4
  phase2_weight: 20.43
  phase3_weight: 42.29
  phase4_weight: 3.88


global:
  max_concurrent: 10
  max_for_phase_1: 3
  minimum_minutes_between_jobs: 5


jobs:
  - name: sabrient_1
    max_plots: 999
    farmer_public_key:
    pool_public_key:
    temporary_directory: /plotter/1
    temporary2_directory:
    destination_directory:
      - /media/farm1/plots
      - /media/farm2/plots
      - /media/farm3/plots
    size: 32
    bitfield: true
    threads: 28
    buckets: 128
    memory_buffer: 20000
    max_concurrent: 6
    max_concurrent_with_start_early: 7
    initial_delay_minutes: 0
    stagger_minutes: 60
    max_for_phase_1: 3
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false
    exclude_final_directory: false
    skip_full_destinations: true
    unix_process_priority: 10
    windows_process_priority: 32
    enable_cpu_affinity: false
    cpu_affinity: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23 ]
```

```
========================================================================================================================
num    job     k    plot_id    pid           start          elapsed_time   phase   phase_times   progress   temp_size
========================================================================================================================
1     sabrient_1   32   447af97   85778   2021-05-23 13:51:31   00:21:28       1                     3.59%      63 GiB
========================================================================================================================
Manager Status: Running

========================================================================
type      drive         used      total       %      #    temp   dest
========================================================================
t/-    /plotter/1     0.06TiB    1.82TiB    3.2%    1/-   1
-/d    /media/farm1   10.69TiB   10.91TiB   98.0%   -/1          1
-/d    /media/farm2   2.97TiB    12.73TiB   23.3%   -/-
-/d    /media/farm3   0.00TiB    12.73TiB   0.0%    -/-
========================================================================
CPU Usage: 6.5%
RAM Usage: 7.22/188.83GiB(4.5%)

Plots Completed Yesterday: 0
Plots Completed Today: 0

Next log check at 2021-05-23 14:14:00
```
